apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-yrwh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-yrwh
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-yrwh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-yrwh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-yrwh
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-rcrj-tenant/rhtap-demo-app/hacbs-test-project-yrwh@sha256:04ae3241c3058819f6c0ee6235ea41d78c616b79a82843787582114f9531411a
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
